### ISSUE TITLE
Error setting challenge

### ISSUE THREAD

**Issue by jacobgibbs** [AirConsole/letsencrypt#1]
Hey, 

I have run through the installation instructions and deploy to appengine. I have tried the curl command in OSX Terminal and also Google Cloud Shell but I'm getting the same error (log below).

I have limited knowledge of Python, so can't really see where it's going wrong on line 244 other than that the response code hasn't come back as 200 (which I presume is because there's an error creating the challenge file).

`Generate account key...
Generate domain key...
Generate csr...
Parsing account key...
Parsing CSR...
Registering account...
Registered!
Verifying www.xxxxx.co.uk...
Setting challenge www.xxxxx.co.uk...
Traceback (most recent call last):
  File "<stdin>", line 332, in <module>
  File "<stdin>", line 329, in main
  File "<stdin>", line 244, in get_crt
ValueError: Error setting challenge on http://www.xxxxx.co.uk/.well-known/acme-challenge/`

**Comment by anotherstarburst** [comment]
This seems to only affect some sites. I've just grabbed an ssl cert using this lib for one website. Then the next website produced the error you describe.
