### ISSUE TITLE
Updated agreement PDF

### ISSUE THREAD

**Issue by hypertexthero** [AirConsole/letsencrypt#3]
I got the following error:

```
Registering account...
Traceback (most recent call last):
  File "<stdin>", line 332, in <module>
  File "<stdin>", line 329, in main
  File "<stdin>", line 212, in get_crt
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1
.1.1-August-1-2016.pdf]",
  "status": 400
}
```

…and needed to [fork your script and update the hard-coded agreement URL](https://github.com/hypertexthero/letsencrypt/blob/master/__init__.py#L205) in order for it to work. 

Thanks much for this script — very useful!

**Comment by anotherstarburst** [comment]
Yes indeed - same issue. Apparently you'll need to apply this update: https://github.com/roots/trellis/pull/624144

Thanks for the script though - awesome!
